version: 2

defaults: &defaults
    working_directory: ~/reither
    docker:
        - image: circleci/node:8.10

jobs:
    test:
        <<: *defaults
        steps:
            - checkout

            - restore_cache:
                    keys:
                        - v1-dependencies-{{ checksum "package.json" }}
                        - v1-dependencies-

            - run: npm install
            - run:
                name: Run linter
                command: npm run lint
            - run:
                name: Run flow
                command: npm run flow
            - run:
                name: Run tests
                command: npm test

            - save_cache:
                    paths:
                        - node_modules
                    key: v1-dependencies-{{ checksum "package.json" }}

            - persist_to_workspace:
                root: ~/reither
                paths: .

    deploy:
        <<: $defaults
        steps:
            - attach_workspace:
                at: ~/reither
            - run:
                name: Authenticate with registry
                command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/reither/.npmrc
            - run:
                name: Publish package
                command: npm publish

workflows:
    version: 2
    test-deploy:
        jobs:
            - test
            - deploy
                requires:
                    - test
                filters:
                    tags:
                        only: /^v[0.9]+\.[0.9]+\.[0.9]+$/
                    branches:
                        ignore: /.*/
